# crowdin.yaml
#
# Crowdin configuration file for CyanogenMod
#
# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

project_identifier: cyanogenmod
api_key: your_api_key
base_path: your/path
preserve_hierarchy: true

files:
  # Default for AOSP projects with CM additions
  -
    source:      '/**/values/cm_*.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: &anchor
      android_code:
        af: af
        am: am
        ar: ar
        az: az
        be: be
        bg: bg
        ca: ca
        cs: cs
        da: da
        de: de
        el: el
        es-ES: es
        fa: fa
        fi: fi
        fr: fr
        he: iw
        hi: hi
        hr: hr
        hu: hu
        hy: hy
        id: in
        it: it
        ja: ja
        ka: ka
        km: km
        ko: ko
        ku: ku
        lo: lo
        lt: lt
        lv: lv
        ml: ml
        mn: mn
        ms: ms
        nb: nb
        ne: ne
        nl: nl
        pa: pa
        pl: pl
        rm: rm
        ro: ro
        ru: ru
        si: si
        sk: sk
        sl: sl
        sr: sr
        sv-SE: sv
        sw: sw
        ta: ta
        th: th
        tl: tl
        tr: tr
        uk: uk
        vi: vi
        zu: zu
    ignore:
      - /**/cm_extra.xml
      - /**/cm_colors.xml
      - /**/cm_dimens.xml
      - /**/Launcher3/**/*.xml

  # Default for device apps
  -
    source:      '/device/**/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
    ignore:
      - /device/google/**/*.xml
      - /device/sample/**/*.xml
      - /device/**/overlay/**/*.xml
  -
    source:      '/device/**/values/plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
    ignore:
      - /device/google/**/*.xml
      - /device/sample/**/*.xml
      - /device/**/overlay/**/*.xml
  -
    source:      '/device/**/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
    ignore:
      - /device/google/**/*.xml
      - /device/sample/**/*.xml
      - /device/**/overlay/**/*.xml
  # Default for CM apps (CMAccount, CMFM etc.)
  -
    source:      '/packages/apps/CM*/**/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
    ignore:
      - /packages/apps/CM*/tests/**/*.xml
  -
    source:      '/packages/apps/CM*/**/values/plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
    ignore:
      - /packages/apps/CM*/tests/**/*.xml
  -
    source:      '/packages/apps/CM*/**/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
    ignore:
      - /packages/apps/CM*/tests/**/*.xml

# Other projects

  # Apollo
  -
    source:      '/packages/apps/Apollo/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Apollo/res/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Apollo/res/values/plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # BluetoothExt
  -
    source:      '/packages/apps/BluetoothExt/res/values/strings*.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Camera2 (qcomstrings.xml)
  -
    source:      '/packages/apps/Camera2/res/values/qcomstrings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # DSPManager
  -
    source:      '/packages/apps/DSPManager/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/DSPManager/res/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # LockClock
  -
    source:      '/packages/apps/LockClock/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/LockClock/res/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Torch
  -
    source:      '/packages/apps/Torch/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # VoicePlus
  -
    source:      '/packages/apps/VoicePlus/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Galaxy4
  -
    source:      '/packages/wallpapers/Galaxy4/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # ThemeChooser
  -
    source:      '/vendor/tmobile/**/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Superuser
  -
    source:      '/external/koush/Superuser/Superuser/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # WhisperPush
  -
    source:      '/external/whispersystems/WhisperPush/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Device specific packages

  # fmapp2
  -
    source:      '/hardware/qcom/fm/fmapp2/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/hardware/qcom/fm/fmapp2/res/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # FMRecord
  -
    source:      '/hardware/qcom/fm/FMRecord/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # SamsungServiceMode
  -
    source:      '/packages/apps/SamsungServiceMode/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
